// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Flyboy",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Flyboy",
            targets: ["AppModule"],
            bundleIdentifier: "com.cobo.flyboyadventuregame",
            teamIdentifier: "4U5LUB477B",
            displayVersion: "1.0",
            bundleVersion: "5",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            appCategory: .arcadeGames
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
